import { Inter } from "next/font/google";
import Link from "next/link";
import { Button, Flex, Layout, Menu, Space } from "antd";
import Sider from "antd/es/layout/Sider";
import { Content, Footer, Header } from "antd/es/layout/layout";
import {
  PhoneOutlined,
  CarryOutOutlined,
  ShopOutlined,
  CarOutlined,
  ShoppingOutlined,
  FireOutlined,
  HomeOutlined,
} from "@ant-design/icons";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getItem(label, key, icon) {
  return {
    key,
    icon,
    label,
  };
}

const items = [
  getItem("View all orders", "1", <FireOutlined />),
  getItem("Today's order", "2", <ShoppingOutlined />),
  getItem("Today's delivery", "3", <CarOutlined />),
  getItem("Contact list", "4", <PhoneOutlined />),
  getItem("Ready for pickup", "5", <CarryOutOutlined />),
  getItem("View distributors", "6", <ShopOutlined />),
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <Layout>
            <Flex horizontal style={{ minHeight: "100vh" }}>
              <Sider theme="dark" className="sider">
                <Flex justify="center">
                  <Button
                    type="primary"
                    shape="circle"
                    icon={<HomeOutlined />}
                  />
                </Flex>
                <Menu
                  theme="dark"
                  defaultSelectedKeys={["1"]}
                  mode="inline"
                  items={items}
                />
              </Sider>
              <Layout>
                <Header>Special Order System</Header>
                <Content>{children}</Content>
                <Footer>Footer</Footer>
              </Layout>
            </Flex>
          </Layout>
        </main>
      </body>
    </html>
  );
}
