import { Inter } from "next/font/google";
import "./globals.css";
import { Breadcrumb, Layout, Menu, theme } from "antd";
//const { Header, Content, Footer, Sider } = Layout;
import Sider from "antd/es/layout/Sider";

import {
  HomeOutlined,
  DiffOutlined,
  PhoneOutlined,
  DesktopOutlined,
  FileOutlined,
  PieChartOutlined,
  TeamOutlined,
  UserOutlined,
} from "@ant-design/icons";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getItem(label, key, icon, children, anything) {
  return {
    key,
    icon,
    children,
    label,
    anything,
  };
}

const handleClick = (link) => {};

const items = [
  getItem(<Link href="/">Dashboard</Link>, "1", <PieChartOutlined />),
  getItem(
    <Link href="/today">Today&apos;s orders</Link>,
    "2",
    <DiffOutlined />
  ),
  getItem(<Link href="/call">Call list</Link>, "3", <PhoneOutlined />),

  // getItem("Option 1", "51", <HomeOutlined />),
  // getItem("Option 2", "52", <DesktopOutlined />),
  // getItem("User", "sub1", <UserOutlined />, [
  //   getItem("Tom", "53"),
  //   getItem("Bill", "4"),
  //   getItem("Alex", "5"),
  // ]),
  // getItem("Team", "sub2", <TeamOutlined />, [
  //   getItem("Team 1", "6"),
  //   getItem("Team 2", "8"),
  // ]),
  // getItem("Files", "9", <FileOutlined />),
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div>
        <body className={inter.className}>
          <Layout hasSider style={{ height: "100vh" }}>
            <Sider
              style={{
                borderRadius: "0 30px 30px 0",
                backgroundColor: "rgb(25,25,25)",
                // padding: "0 26px 0 0",
              }}
            >
              <div className="demo-logo-vertical" />
              <Menu
                theme="dark"
                defaultSelectedKeys={["1"]}
                mode="inline"
                items={items}
                style={{
                  borderRadius: "0 30px 30px 0",
                  backgroundColor: "rgb(0,0,0)",
                }}
              />
            </Sider>
            {children}
          </Layout>
        </body>
      </div>
    </html>
  );
}
